export const mobileAssets = {
  heroPhoto: "/media/figma/portrait.png",
  heroWolf: "/media/mobile/mobile-hero-wolf.png",
  heroProjectLogos: [
    "/media/figma/hero-project-logo1.png",
    "/media/figma/hero-project-logo2.png",
    "/media/figma/hero-project-logo3.png",
    "/media/figma/hero-project-logo4.png",
    "/media/figma/hero-project-logo5.png",
    "/media/figma/hero-project-logo6.png",
    "/media/figma/hero-project-logo7.png",
    "/media/figma/hero-project-logo8.png",
    "/media/figma/hero-project-logo9.png",
    "/media/figma/hero-project-logo10.png",
  ],
  atomLogo: "/media/figma/Case/Atom/Atom logo.png",
  atomCarSide: "/media/figma/atom-car-side.png",
  atomSteering: "/media/figma/atom-main-steering.png",
  atomKamaz: "/media/figma/atom-kamaz.svg",
  atomCards: "/media/figma/atom-cards.png",
  atomSmallPhoto: "/media/figma/atom-small-photo.jpg",
  atomThin: "/media/figma/atom-thin.png",
  atomRadar: "/media/figma/atom-radar.png",
  atomLast: "/media/figma/atom-final.png",
  objLogo: "/media/figma/Case/Obj/OBJ logo.png",
  objDescription: "/media/figma/obu-description.svg",
  objCar: "/media/figma/obu-car.png",
  objMusic: "/media/figma/obu-music.png",
  pochtaLogo: "/media/figma/Case/PB/logo.png",
  pochtaPhone: "/media/mobile/mobile-pochta-phone.png",
  pochtaCopyCard: "/media/mobile/mobile-pochta-card.png",
  pochtaFastPay: "/media/mobile/mobile-pochta-fast-pay.png",
  pochtaMsc: "/media/mobile/mobile-pochta-msc.png",
  pochtaPlashki: "/media/mobile/mobile-pochta-plashki.png",
  bitrixLogo: "/media/figma/Case/Bitrix24 logo.png",
  bitrixFacesCombined: "/media/mobile/mobile-bitrix-faces.png",
  bitrixFaceOne: "/media/figma/bitrix-face-one.png",
  bitrixFaceTwo: "/media/figma/bitrix-face-two.jpg",
  bitrixFaceThree: "/media/figma/bitrix-face-three.png",
  bitrixFaceFour: "/media/figma/bitrix-face-four.png",
  bitrixFaceFive: "/media/figma/bitrix-face-five.png",
  bitrixFileIcon: "/media/mobile/mobile-bitrix-file-icon.svg",
  bitrixLikeIcon: "/media/mobile/mobile-bitrix-like-icon.svg",
  bitrixBrushIcon: "/media/mobile/mobile-bitrix-brush-icon.svg",
  bitrixBlock: "/media/mobile/mobile-bitrix-block.png",
  bitrixLast: "/media/mobile/mobile-bitrix-last.png",
  stolotoLogo: "/media/figma/Case/Stoloto/logo.png",
  stolotoBlock: "/media/mobile/mobile-stoloto-block.png",
  stolotoTwoMatryoshkas: "/media/mobile/mobile-stoloto-two-matryoshkas.png",
  stolotoSingleMatryoshka: "/media/mobile/mobile-stoloto-single-matryoshka.png",
  stolotoLotteries: "/media/figma/stoloto-lotteries.png",
  stolotoRight: "/media/mobile/mobile-stoloto-right.png",
  additionalMoskvichLogo: "/media/figma/additional-moskvich-logo.svg",
  additionalMoskvichImage: "/media/figma/additional-moskvich-image.png",
  additionalKulturaLogo: "/media/figma/additional-kultura-logo.svg",
  additionalKulturaImage: "/media/figma/additional-kultura-image.png",
  additionalStolotoDotsLogo: "/media/figma/additional-stoloto-dots-logo.svg",
  additionalStolotoDotsImage: "/media/figma/additional-stoloto-dots-image.png",
  additionalPostamatLogo: "/media/figma/additional-postamat-logo.png",
  additionalPostamatImage: "/media/figma/additional-postamat-image.png",
  additionalAuchanLogo: "/media/figma/additional-auchan-logo.svg",
  additionalAuchanImage: "/media/figma/additional-auchan-image.png",
  additionalHaierLogo: "/media/figma/additional-haier-logo.png",
  additionalHaierImage: "/media/figma/additional-haier-image.png",
  additionalBorishoffLogo: "/media/figma/additional-borishoff-logo.svg",
  additionalBorishoffImage: "/media/figma/additional-borishoff-image.png",
  additionalFinanceLogo: "/media/figma/additional-finance-logo.png",
  additionalFinanceImage: "/media/figma/additional-finance-image.png",
} as const;

export const mobileHeroProjects = [
  "ATOM auto",
  "Pochta bank,",
  "Bitrix24,",
  "Stoloto,",
  "Auchan,",
  "Moskvich,",
  "Haier,",
  "Borishoff,",
  "Moscow Postamat",
  "Culture of MSC",
  "and more",
] as const;
